import Head from "next/head";
import { Inter } from "next/font/google";
import { Box } from "@mui/material";
import ToggleButton from "../src/components/toggleButton";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Dhruv K</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Box
				sx={{
					minHeight: "100vh",
					padding: 2,
					backgroundColor: "primary.main",
					border: "1px solid red",
				}}
			>
				<p>Page Content</p>
				{/* <ToggleButton /> */}
			</Box>
		</>
	);
}
