import Head from "next/head";
import { Inter } from "next/font/google";
import { Box } from "@mui/material";
import ToggleButton from "../src/components/toggleButton";
import Hero from "@/src/components/Hero/Hero";
import PageSection from "../src/components/PageSection/PageSection";
import CardDiv from "@/src/components/Cards/CardDiv";
import CardTitle from "@/src/components/Cards/CardTitle";
import ScrollCard from "@/src/components/Scroll/ScrollCard";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Dhruv K</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Box
				sx={{
					minHeight: { xs: "100vh", sm: "50vh", md: "100vh" },
					marginX: "5vw",
					padding: 2,
					backgroundColor: "primary.main",
					border: "1px solid red",
				}}
			>
				<Hero />
			</Box>
			<PageSection>
				<ScrollCard />
			</PageSection>
		</>
	);
}
{
	/* <ToggleButton /> */
}
